# Use the gcc 13.1 as a base image
FROM gcc:13.1

# Set metadata
LABEL maintainer="Jojo Calabra"

# Set the working directory
WORKDIR /src

# Install dependencies
RUN apt-get update && apt-get install -y --quiet cmake libgtest-dev libboost-test-dev && rm -rf /var/lib/apt/lists/*

# Copy the source code into the container
COPY . .

# Command to build and run the server when the container is started
CMD cmake . -B ./build && make -C ./build && ./build/APIServer
